### ISSUE TITLE
Issues parsing .scalafmt on example project

### ISSUE THREAD

**Issue by andrewmeyerBR** [olafurpg/scalafmt#397]
I was having issues running `sbt scalafmtTest` with customizations to the `.scalafmt` file, so I tried with the example project at https://github.com/olafurpg/sbt-scalafmt-example but got the same result.

Changing `.scalafmt` to:

```
--style IntelliJ
--maxColumn 40
```

or similarly:

```
--style default
--maxColumn 40
--continuationIndentCallSite 2
--continuationIndentDefnSite 2
--alignByOpenParenCallSite false
--configStyleArguments false
--danglingParentheses true
```

results in the following output. Note that running from the CLI using `scalafmt --config /path/to/.scalafmt -f /path/to/file.scala` seems to work fine, so I believe it's a plugin issue. You should be able to reproduce this behavior easily using the example github project.

Output:
```scala
org.scalafmt.Error$InvalidScalafmtConfiguration: Unable to parse scalafmt configuration file: /Users/andrew.meyer/Desktop/sbt-scalafmt-example-master/.scalafmt
	at org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:19)
	at org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:19)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:84)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at org.scalafmt.sbt.HasScalaFmt.testProjectIsFormatted(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$6.apply(ScalaFmtPlugin.scala:109)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$6.apply(ScalaFmtPlugin.scala:109)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.scalafmt.Error$InvalidScalafmtConfiguration: Unable to parse scalafmt configuration file: /Users/andrew.meyer/Desktop/sbt-scalafmt-example-master/.scalafmt
	at org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:19)
	at org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:19)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:84)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at org.scalafmt.sbt.HasScalaFmt.testProjectIsFormatted(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$6.apply(ScalaFmtPlugin.scala:109)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$6.apply(ScalaFmtPlugin.scala:109)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
org.scalafmt.Error$InvalidScalafmtConfiguration: Unable to parse scalafmt configuration file: /Users/andrew.meyer/Desktop/sbt-scalafmt-example-master/.scalafmt
	at org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:19)
	at org.scalafmt.cli.Scalafmt210$$anonfun$1.apply(Scalafmt210.scala:19)
	at scala.Option.getOrElse(Option.scala:121)
	at org.scalafmt.cli.Scalafmt210.format(Scalafmt210.scala:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:84)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at org.scalafmt.sbt.HasScalaFmt.testProjectIsFormatted(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$6.apply(ScalaFmtPlugin.scala:109)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$6.apply(ScalaFmtPlugin.scala:109)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (sbt-scalafmt-example-master/compile:scalafmtTest) org.scalafmt.Error$InvalidScalafmtConfiguration: Unable to parse scalafmt configuration file: /Users/andrew.meyer/Desktop/sbt-scalafmt-example-master/.scalafmt
[error] (project1/compile:scalafmtTest) org.scalafmt.Error$InvalidScalafmtConfiguration: Unable to parse scalafmt configuration file: /Users/andrew.meyer/Desktop/sbt-scalafmt-example-master/.scalafmt
[error] (project2/compile:scalafmtTest) org.scalafmt.Error$InvalidScalafmtConfiguration: Unable to parse scalafmt configuration file: /Users/andrew.meyer/Desktop/sbt-scalafmt-example-master/.scalafmt
[error] Total time: 0 s, completed Aug 9, 2016 7:58:52 PM
```

Using:
* 0.2.6 (example project), 0.2.11 (my project)

**Comment by olafurpg** [comment]
--style intellij was only added in 0.2.12, which I haven't advertised since it only introduced minor changes 0.2.13 is just around the corner.

--configStyleArguments is not exposed as a CLI flag. The SBT plugin prints out this error for me using 0.2.11

```
[info] Formatting 1 Scala source {file:/Users/ollie/dev/sbt-scalafmt-example/}sbt-scalafmt-example ...
Error: Unknown option --configStyleArguments
Error: Unknown argument 'false'
scalafmt 0.2.11
....
```

I've updated the example project to 0.2.12 and .scalafmt to

```
--style IntelliJ
--maxColumn 40
```

Please let me know if that fails for you https://github.com/olafurpg/sbt-scalafmt-example
