### ISSUE TITLE
HasScalaFmt ignores fmtSbtFiles property

### ISSUE THREAD

**Issue by Synesso** [olafurpg/scalafmt#420]
**Version**: 0.3.1
**Integration**: sbt
**Configuration**: defaultWithAlign + formatSbtFiles=false

With `formatSbtFiles false` & an sbt file formatted contrary to scalafmt's wishes, running `sbt test` results in:

```
org.scalafmt.sbt.HasScalaFmt$MisformattedFile: build.sbt is mis-formatted.
	at org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$testFormatted(HasScalaFmt.scala:67)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$1.apply(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$1.apply(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.HasScalaFmt.org$scalafmt$sbt$HasScalaFmt$$handleFile(HasScalaFmt.scala:88)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.HasScalaFmt$$anonfun$testProjectIsFormatted$2.apply(HasScalaFmt.scala:59)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:153)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:306)
	at org.scalafmt.sbt.HasScalaFmt.testProjectIsFormatted(HasScalaFmt.scala:59)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$7.apply(ScalaFmtPlugin.scala:120)
	at org.scalafmt.sbt.ScalaFmtPlugin$$anonfun$configScalafmtSettings$7.apply(ScalaFmtPlugin.scala:120)
```

**Comment by olafurpg** [comment]
Have you tried `formatSbtFiles in ThisBuild := false`? The setting must apply to all settings in a multi-project build.

**Comment by Synesso** [comment]
Setting that property worked. However, it's a single project build.

**Comment by olafurpg** [comment]
Glad it worked

>  However, it's a single project build.

I'm still trying to wrap my head around when sbt creates a new project scope and where it doesn't. Setting `in ThisBuild` or using a `commonSettings: Seq[Def.Setting[_]]` for every `lazy val foo = project(...).settings(commonSettings)` is usually enough to apply settings globally.

**Comment by olafurpg** [comment]
I'm closing this issue since it was resolved.
