### ISSUE TITLE
--stdin not working with nailgun

### ISSUE THREAD

**Issue by AlecZorab** [olafurpg/scalafmt#569]
have nailgun working as expected using `scalafmt -i -f x`, however:

```
➜  ~ ✗ scalafmt -v
scalafmt 0.4.8
➜  ~ ✗ echo "object X {}" > test.scala
➜  ~ ✗ cat test.scala | scalafmt --stdin
java.io.IOException: Unknown stream type: H
        at com.martiansoftware.nailgun.NGInputStream.readHeader(NGInputStream.java:73)
        at com.martiansoftware.nailgun.NGInputStream.read(NGInputStream.java:120)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:72)
        at scala.collection.Iterator$class.foreach(Iterator.scala:893)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:357)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:323)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1336)
        at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:325)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1336)
        at org.scalafmt.cli.InputMethod$StdinCode$.apply(InputMethod.scala:25)
        at org.scalafmt.cli.Cli$.getInputMethods(Cli.scala:119)
        at org.scalafmt.cli.Cli$.runFormat(Cli.scala:175)
        at org.scalafmt.cli.Cli$.run(Cli.scala:54)
        at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:47)
        at org.scalafmt.cli.Cli$.nailMain(Cli.scala:28)
        at org.scalafmt.cli.Cli.nailMain(Cli.scala)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.martiansoftware.nailgun.NGSession.run(NGSession.java:280)
```

**Comment by olafurpg** [comment]
Have you tried restarting the nailgun server?

**Comment by AlecZorab** [comment]
```
cat test.scala | scalafmt --stdin
Starting nailgun...
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on all interfaces, port 2113.
java.io.IOException: Unknown stream type: H
        at com.martiansoftware.nailgun.NGInputStream.readHeader(NGInputStream.java:73)
        at com.martiansoftware.nailgun.NGInputStream.read(NGInputStream.java:120)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
```

**Comment by olafurpg** [comment]
Hmmm. I am unable to reproduce

```
$ echo "object X {}" > test.scala                                                                        converter
$ ollie  ~  dev  paradise  target  cat test.scala| ~/dev/scalafmt/bin/scalafmt_ng --stdin                                                 converter
object X {}
```

However, I have seen a similar error before, but I can't recall what fixed the problem. I'm sorry.

**Comment by olafurpg** [comment]
Is this still a problem?

**Comment by olafurpg** [comment]
Please reopen if this is still a problem
