### ISSUE TITLE
CLI does not want to take config parameters

### ISSUE THREAD

**Issue by dstechenko** [olafurpg/scalafmt#617]
Tried using CLI --config property, and it failed.

**Version**: 0.5.0-RC2
**Integration**: cli

```
typeless:master* λ scalafmt --config "style=defaultWithAlign"
Error: Option --config failed when given 'style=defaultWithAlign'. /Users/dmytro/Projects/typeless/style=defaultWithAlign (No such file or directory)
Try  for more information.
Exception in thread "main" org.scalafmt.Error$UnableToParseCliOptions$: Failed to parse CLI options
	at org.scalafmt.Error$UnableToParseCliOptions$.<clinit>(Error.scala)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:69)
	at org.scalafmt.cli.Cli$.main(Cli.scala:63)
	at org.scalafmt.cli.Cli.main(Cli.scala)
```

**Comment by olafurpg** [comment]
Thanks for reporting! I think this should work: `scalafmt --config "\"style=defaultWithAlign\""`

I agree this is unintuitive. It was supposed to work like you tried but it appears scopt drops the quotes. Maybe we should have a separate flag for passing in configuration as string, something like `--config-str "style=..."`. WDYT?

**Comment by dstechenko** [comment]
@olafurpg yeah, that would be great!
