### ISSUE TITLE
Error when using method in a constructor

### ISSUE THREAD

**Issue by tgodzik** [olafurpg/scalafmt#671]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 40
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
def this(a: Int) = {
this
abc()}
```

Expected, I would like the formatted output to look like this:
```scala
def this(a: Int) = {
    this
    abc()
}
```

Got an error:
```
java.util.NoSuchElementException: next on empty iterator
[info]   at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
[info]   at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
[info]   at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:63)
[info]   at scala.collection.IterableLike$class.head(IterableLike.scala:107)
[info]   at scala.meta.tokens.Tokens.scala$collection$IndexedSeqOptimized$$super$head(Tokens.scala:29)
[info]   at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:126)
[info]   at scala.meta.tokens.Tokens.head(Tokens.scala:29)
[info]   at org.scalafmt.util.TreeOps$$anonfun$addAll$1$1.apply(TreeOps.scala:91)
[info]   at org.scalafmt.util.TreeOps$$anonfun$addAll$1$1.apply(TreeOps.scala:90)
[info]   at scala.collection.immutable.List.foreach(List.scala:381)
[info]   ...
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is a bug, will be fixed in 0.5.2 : )
