### ISSUE TITLE
Malformed xml literal for matching nodes in xml node

### ISSUE THREAD

**Issue by tgodzik** [olafurpg/scalafmt#673]
This template is a guideline, not a strict requirement.
- **Version**: 0.5
- **Integration**: IntelliJ
- **Configuration**:
```
maxColumn = 40
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
value match {            case <tr>{ cells @ _*}</tr> => 123}
```

Expected, I would like the formatted output to look like this:
```scala
value match { case <tr>{ cells @ _* }</tr> => 123 }
```

Did not format at all, got an error:
```
scala.meta.tokenizers.TokenizeException: <input>:1: error: malformed xml literal
[info] value match {            case <tr>{ cells @ _*}</tr> => 123}
[info]                               ^
[info]   at scala.meta.internal.tokenizers.Reporter$class.syntaxError(Reporter.scala:26)
[info]   at scala.meta.internal.tokenizers.Reporter$$anon$1.syntaxError(Reporter.scala:35)
[info]   at scala.meta.internal.tokenizers.Reporter$class.syntaxError(Reporter.scala:28)
[info]   at scala.meta.internal.tokenizers.Reporter$$anon$1.syntaxError(Reporter.scala:35)
[info]   at scala.meta.internal.tokenizers.LegacyScanner.getXml(LegacyScanner.scala:961)
[info]   at scala.meta.internal.tokenizers.LegacyScanner.fetchLT$1(LegacyScanner.scala:336)
[info]   at scala.meta.internal.tokenizers.LegacyScanner.fetchToken(LegacyScanner.scala:344)
[info]   at scala.meta.internal.tokenizers.LegacyScanner.nextToken(LegacyScanner.scala:233)
[info]   at scala.meta.internal.tokenizers.LegacyScanner.foreach(LegacyScanner.scala:1022)
[info]   at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:154)
```

**Comment by tgodzik** [comment]
Got a couple more errors once I run scalafmt on over 1.5 mln lines of code. I'll add those too when I manage to reproduce a minimal example and then I'll probably try to fix some of them.

**Comment by tgodzik** [comment]
I added a comments to scalameta's https://github.com/scalameta/scalameta/issues/312 since it seems to be scalameta error. Maybe we should close this @olafurpg ?

**Comment by olafurpg** [comment]
Thanks for reporting the issues there. Yes, we can close this issue.
