### ISSUE TITLE
Unable to format when unnecessary parentheses and curly brackets are used.

### ISSUE THREAD

**Issue by tgodzik** [olafurpg/scalafmt#716]
This template is a guideline, not a strict requirement.
- **Version**: 0.5.4
- **Integration**: IntelliJ
- **Configuration**:
```
style=default
```

## Unexpected formatting output

Obtained, scalafmt formats code like this:
```scala
class A {

  (Range(0, 10)).map { (i =>
      println{
        i
      }
    )
    }
}
```

Expected, I would like the formatted output to look like this:
```scala
class A {
  (Range(0, 10)).map { (i =>println{ i } ) }
}
```

Now it throws an error:
```
org.scalafmt.Error$FormatterOutputDoesNotParse: Formatter output does not parse:
[info] class A {
[info]
[info]   (Range(0, 10)).map { (i => println
[info]                                    ^
[info] <input>:3: error: ) expected but end of file found
[info] (Range(0, 10)).map { (i => println
[info]                                      ^
[info]
[info] class A {
[info]
[info]   (Range(0, 10)).map { (i => println
[info]   at org.scalafmt.util.FormatAssertions$class.assertFormatPreservesAst(FormatAssertions.scala:37)
[info]   at org.scalafmt.FormatTests.assertFormatPreservesAst(FormatTests.scala:32)
[info]   at org.scalafmt.FormatTests.run(FormatTests.scala:69)
[info]   at org.scalafmt.FormatTests$$anonfun$4.apply(FormatTests.scala:54)
[info]   at org.scalafmt.FormatTests$$anonfun$4.apply(FormatTests.scala:54)
[info]   at org.scalafmt.util.HasTests$$anonfun$runTest$2.apply$mcV$sp(HasTests.scala:156)
[info]   at org.scalafmt.util.HasTests$$anonfun$runTest$2.apply(HasTests.scala:151)
[info]   at org.scalafmt.util.HasTests$$anonfun$runTest$2.apply(HasTests.scala:151)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   ...
```

Tested using a stat file:
```
style = default
<<< ONLY unnecessary parantheses
class A {

  (Range(0, 10)).map { (i =>
      println{
        i
      }
    )
    }
}
>>>
class A {
  (Range(0, 10)).map { (i => println{i})}
}
```

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce. Is this a real-world example or are you fuzzing? You have an eye for finding scalafmt bugs :) 

Note that the parentheses are redundant, using both parens and curly braces is like wearing a with suspenders!

**Comment by tgodzik** [comment]
It's just a thing I found in our code. I just removed the redundant parens from there, but I figured if someone added it then it's possible they'll do it again. It's not really world breaking, but I thought it's good to at least report it.

**Comment by olafurpg** [comment]
Definitely good to report. This is a bug.

**Comment by olafurpg** [comment]
This was caused by a problematic case in Router.scala that should be removed in the next major release, see #768
