### ISSUE TITLE
 scalafmt --diff appears to break on deleted files

### ISSUE THREAD

**Issue by caoilte** [olafurpg/scalafmt#759]
- **Version**: 0.5.7

I staged a file for deleting from commit and now `scalafmt --diff` (CLI) exits with

```
Exception in thread "main" java.io.FileNotFoundException: /Users/caoilte/personal/scala/test/src/main/scala/Test.scala (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:58)
	at org.scalafmt.util.FileOps$.readFile(FileOps.scala:47)
	at org.scalafmt.cli.InputMethod$FileContents.readInput(InputMethod.scala:39)
	at org.scalafmt.cli.Cli$.org$scalafmt$cli$Cli$$handleFile(Cli.scala:139)
	at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:215)
	at org.scalafmt.cli.Cli$$anonfun$runFormat$1.apply(Cli.scala:213)
```

**Comment by olafurpg** [comment]
Thanks for reporting! -diff has been discussed in https://github.com/olafurpg/scalafmt/issues/720. It seems we should move to `status --porcelain` (which includes removed/edited/new status per file) from `diff --name-only` (which lists files only). A good place to start fixing this issue is here https://github.com/olafurpg/scalafmt/blob/ee52411bef096d1ae30add30b7c5f9eafebb5fc9/utils/src/main/scala/org/scalafmt/util/GitOps.scala#L65-L74
