### ISSUE TITLE
Not resolving config before using it

### ISSUE THREAD

**Issue by dwijnand** [olafurpg/scalafmt#765]
- **Version**: 0.5.7
- **Integration**: CLI
- **Configuration**:
```
rewrite.rules = []
rewrite.rules += RedundantBraces
rewrite.rules += RedundantParens
rewrite.rules += SortImports
```

## Steps

Run `scalafmt`

## Problem

```
Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: called unwrapped() on value with unresolved substitutions, need to Config#resolve() first, see API docs
	at com.typesafe.config.impl.ConfigDelayedMerge.unwrapped(ConfigDelayedMerge.java:52)
	at com.typesafe.config.impl.SimpleConfigObject.unwrapped(SimpleConfigObject.java:210)
	at com.typesafe.config.impl.SimpleConfigObject.unwrapped(SimpleConfigObject.java:25)
	at com.typesafe.config.impl.SimpleConfigObject.unwrapped(SimpleConfigObject.java:210)
	at org.scalafmt.config.hocon.Hocon2Class$.config2map(Hocon2Class.scala:21)
	at org.scalafmt.config.hocon.Hocon2Class$.gimmeConfig(Hocon2Class.scala:34)
	at org.scalafmt.config.hocon.Hocon2Class$.gimmeClass(Hocon2Class.scala:44)
	at org.scalafmt.config.Config$.fromHocon(Config.scala:40)
	at org.scalafmt.cli.CliOptions$$anonfun$org$scalafmt$cli$CliOptions$$tryDirectory$2.apply(CliOptions.scala:59)
	at org.scalafmt.cli.CliOptions$$anonfun$org$scalafmt$cli$CliOptions$$tryDirectory$2.apply(CliOptions.scala:56)
	at scala.Option$WithFilter.flatMap(Option.scala:208)
	at org.scalafmt.cli.CliOptions$.org$scalafmt$cli$CliOptions$$tryDirectory(CliOptions.scala:56)
	at org.scalafmt.cli.CliOptions$.tryCurrentDirectory(CliOptions.scala:74)
	at org.scalafmt.cli.CliOptions$.auto(CliOptions.scala:35)
	at org.scalafmt.cli.Cli$$anonfun$getConfig$1.apply(Cli.scala:74)
	at org.scalafmt.cli.Cli$$anonfun$getConfig$1.apply(Cli.scala:74)
	at scala.Option.map(Option.scala:146)
	at org.scalafmt.cli.Cli$.getConfig(Cli.scala:74)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:62)
	at org.scalafmt.cli.Cli$.main(Cli.scala:58)
	at org.scalafmt.cli.Cli.main(Cli.scala)
```

## Expectation

Less stacks, more formatting.

## Workaround

Never stray from the beaten path. Write it exactly like the config tells you:

```
rewrite.rules = [RedundantBraces, RedundantParens, SortImports]
```

**Comment by olafurpg** [comment]
Hmm, the config should be resolved, I thought this got fixed in https://github.com/olafurpg/scalafmt/pull/681/files.

It seems that fix only works if you define `style: ZZZ` in the config. A complete solution would be to resolve the config on line 21 instead of 34 https://github.com/olafurpg/scalafmt/blob/278c31504c612e317dbcc715502984715bf92832/core/src/main/scala/org/scalafmt/config/hocon/Hocon2Class.scala#L21

**Comment by dwijnand** [comment]
Cross-linking. Looks like this is going to regress in the next release of scalafmt.

See https://github.com/scalameta/scalafmt/issues/811#issuecomment-289785732
